### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by hadogenes** [ros-noetic-arch/ros-noetic-rqt-reconfigure#2]
There is missing make dependency for ros-noetic-roslint

**Comment by acxz** [comment]
Ah yep you are right, it also is outdated with 0.5.3 being released. I'm busy this week, but if you submit a PR I'll merge it in a jiffy!

**Comment by acxz** [comment]
Had some time and pushed out the latest package version along with the roslint dep. Thx for the bug report, @hadogenes !
